version: '3.9'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - proxy-tier
    depends_on:
      - nginx-proxy

  web-app:
    image: grubesic/angular-shop:latest
    container_name: web-app
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=minitasa.site
      - LETSENCRYPT_HOST=minitasa.site
      - LETSENCRYPT_EMAIL=your-email@example.com
    networks:
      - proxy-tier
    depends_on:
      - nginx-proxy

networks:
  proxy-tier:
    name: proxy-tier

volumes:
  certs:
  vhost:
  html:
